// client/src/app/google-shopping-feed.xml/route.ts
// Serves the Google Merchant Center product feed at /google-shopping-feed.xml
// Proxies the XML generated by the Express server; cached + revalidated daily.
import { NextResponse } from 'next/server';

export const revalidate = 86400; // 24 hours

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api';

export async function GET() {
  try {
    const upstream = await fetch(`${API_URL}/sitemap/google-shopping-feed.xml`, {
      next: { revalidate: 86400 },
    });

    if (!upstream.ok) {
      throw new Error(`Upstream responded with ${upstream.status}`);
    }

    const xml = await upstream.text();

    return new NextResponse(xml, {
      headers: {
        'Content-Type':  'application/xml; charset=utf-8',
        'Cache-Control': 'public, max-age=86400, stale-while-revalidate=3600',
      },
    });
  } catch (err) {
    console.error('[google-shopping-feed]', err);
    return new NextResponse(
      '<?xml version="1.0" encoding="UTF-8"?><error>Feed temporarily unavailable</error>',
      { status: 502, headers: { 'Content-Type': 'application/xml' } }
    );
  }
}
